	SELECT 
		'SELECT Count(*) FROM [' + TABLE_CATALOG + '].[' + TABLE_SCHEMA + '].[' + TABLE_NAME + '] WHERE [' + COLUMN_NAME + '] IS NULL'
		,TABLE_CATALOG AS DbName
		,TABLE_SCHEMA AS SchemaName
		,TABLE_NAME AS TableName
		,COLUMN_NAME AS ColName
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_CATALOG + TABLE_SCHEMA + TABLE_NAME IN (SELECT TABLE_CATALOG + TABLE_SCHEMA + TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE')
	--AND DATA_TYPE NOT IN ('bit','image','uniqueidentifier','varbinary','xml')
	AND DATA_TYPE NOT IN ('bit','image','varbinary','xml')
	AND TABLE_NAME = 'rm_request'

